### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by Levino** [beevelop/docker-nginx-basic-auth#1]
Nice tool, how about allowing multiple users and password as an environment variable / array?

**Comment by beevelop** [comment]
This is already possible by separating the users by newline. To pass the newlines properly you need to use Shell Quoting (like `$'foo\nbar'`):
```
docker run -d --link web:web --name auth \
           -e HTPASSWD=$'foo:$apr1$odHl5EJN$KbxMfo86Qdve2FH4owePn.\ntest:$apr1$LKkW8P4Y$P1X/r2YyaexhVL1LzZAQm.' \
           beevelop/nginx-basic-auth
```
results in 2 users (`foo:bar` and `test:test`).
