### ISSUE TITLE
how is the password encrypted

### ISSUE THREAD

**Issue by vivekbny** [beevelop/docker-nginx-basic-auth#13]
Hi,

@beevelop I have been using your project and i see the password is encrypted.

Can you please let me know how to make the password encrypted

Thanks,
Vivek

**Comment by beevelop** [comment]
You can generate `htpasswd` credentials using the cli by running:
```sh
htpasswd -n username
# enter the password twice and the desired output should be printed
```

**Comment by beevelop** [comment]
@vivekbny Closing this one for now. Feel free to reopen / open a new issue if you encounter any further problems / questions.
