### ISSUE TITLE
Consider documenting docker-compose.yml or docker-cloud.yml

### ISSUE THREAD

**Issue by jeremydouglass** [beevelop/docker-nginx-basic-auth#15]
Consider documenting how your example works differently with docker-compose.yml or docker-cloud.yml.

Because the examples define HTPASSWD as an environment variable, they often pass strings with $ characters. When using Docker compose or swarm to parse the config file, this will cause the file to fail due to failed string expansion:

> "$ characters must be escaped with a second $"

So your example 

    -e HTPASSWD='foo:$apr1$odHl5EJN$KbxMfo86Qdve2FH4owePn.' \

Will, in the yml config, have double-$$, or it will fail:

    environment:
      - HTPASSWD='foo:$$apr1$$odHl5EJN$$KbxMfo86Qdve2FH4owePn.'

For related discussion, see:

https://forums.docker.com/t/docker-swarm-with-compose-file-does-not-recognize-links/42356/4

**Comment by beevelop** [comment]
Good point. Do you mind sharing a full docker-compose example so we can add it to repository for reference?

**Comment by jeremydouglass** [comment]
Happy to. Do you want it as a pull request in a particular place / with a particular file name?
