### ISSUE TITLE
is there any configuration to join other network ?

### ISSUE THREAD

**Issue by budim12** [beevelop/docker-nginx-basic-auth#18]
I have my own docker-composer.yml, and then i wanna use this basic auth for secure my container..
my container was open in 80/TCP, and no any network definition in yml file, but go this error,,
`docker: Error response from daemon: Cannot link to /app, as it does not belong to the default network.`

i'am using 
`$ docker run -d -p 80:80 --link app:app --name auth beevelop/nginx-basic-auth`

**Comment by beevelop** [comment]
I think this issue is being caused by a misconfiguration in the respective `docker-compose.yml`. Feel free to reopen the issue if it still persists.
