### ISSUE TITLE
is there any license info?

### ISSUE THREAD

**Issue by GoebelL** [beevelop/docker-nginx-basic-auth#25]
I am missing license information for the [images on dockerhub](https://hub.docker.com/r/beevelop/nginx-basic-auth/) as well as for this source repo. 
Do you have any plans to provide this work with some open source license, like Apache, BSD, MIT, or similar? How can I use them?

**Comment by beevelop** [comment]
License information (MIT) has been added. Thank you @GoebelL for the headsup 🍻
