### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by grahampugh** [beevelop/docker-nginx-basic-auth#6]
Hi,

I cannot get this to work, I just get 502 Bad Gateway responses. Perhaps you can see a problem with my Docker configuration:

```
    docker run -d --restart=always --name="web" \
        -v /Users/Shared/repo:/munki_repo \
        -p 8765:80 -h web groob/docker-munki

    HTPASSWD_CONTENT=$(sudo head -n 1 /Users/Shared/repo/.htpasswd)
    docker run -d \
        -e HTPASSWD=$HTPASSWD_CONTENT \
        -e FORWARD_PORT=8765 \
        --link web:web -p 8000:80 \
        --name auth \
        beevelop/nginx-basic-auth
```

As you can see, I renamed the web container to try and conform with the proxy pass to http://web:8765, but that didn't work. Any ideas? 

Thanks!
Graham

**Comment by beevelop** [comment]
From you example I guess your targeted container `groob/docker-munki` does expose port 80. So your `FORWARD_PORT` should be 80 – meaning the containers „internal“ port. Additionally exposing `8765` for `groob/docker-munki` is not necessary AFAICT.

Furthermore you are exposing your authenticated container on port `8000` (accessible via http://foobar:8000). If you are getting a `502 Bad Gateway` on port `8765` with the exact snippet from above, it's probably `groob/docker-munki` who is answering your calls.

**Comment by grahampugh** [comment]
Thanks, yes I think I misunderstood that I should point to the internal port - I didn't know that containers could access each other's internal ports.
Thanks for the clarification!

**Comment by beevelop** [comment]
🍻
